# Site settings
title: 扫帚河-中国乡村的缩影
email: leeychee@gmail.com
description: > 
    扫帚河位于皖西地区,一个充满乡土气息的普通乡村.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://broomriver.me" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  leeychee

# Build settings
markdown: kramdown
